In [20]:
import pandas

In [21]:
df = pandas.read_csv('/Users/johnpendenque/Downloads/coiffeurs_lilles.csv')

In [22]:
df = df.astype({'siret': int}, errors='ignore')

In [23]:
df.head(2)

  entreprise address  telephone facebook instagram site  siret email
0  AS BARBER     NaN        NaN      NaN       NaN  NaN    NaN   NaN
1  AS BARBER     NaN        NaN      NaN       NaN  NaN    NaN   NaN

In [24]:
df.sort_values('entreprise', inplace=True)

In [25]:
df.drop_duplicates(subset=['entreprise', 'address'], inplace=True)

In [26]:
df

,entreprise,address,telephone,facebook,instagram,site,siret,email
0,AS BARBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AS COIFFURE,15 pl Catinat 59800 Lille,NaN,https://www.facebook.com/profile.php?id=100042...,NaN,NaN,NaN,NaN
4,Au Delà Du Miroir,111 r Molinel 59800 Lille,NaN,http://facebook.com/Au-del%C3%A0-du-miroir-190...,NaN,https://audeladumiroir.site-solocal.com/,4.394133e+13,au-dela-du-miroir@wanadoo.fr
9,Camille Albane,21 r Hôpital Militaire 59800 Lille,NaN,https://www.facebook.com/profile.php?id=100064...,https://www.instagram.com/camillealbanelille21...,https://salon.camillealbane.com/coiffeur/lille...,NaN,NaN
8,Camille Albane,18 r Pierre Mauroy 59800 Lille,NaN,https://www.facebook.com/CamilleAlbane.LilleRu...,https://www.instagram.com/camillealbane_lille_...,www.pagesjaunes.fr/pros/07422202#,NaN,NaN
10,Delphine Coiffure et Bien Etre,Hellemmes Lille 10 r Ferdinand Mathias Hellem...,NaN,https://www.facebook.com/pages/Dv-m%C3%A9tamor...,NaN,http://www.delphinecoiffureetbienetre.com/,5.379503e+13,NaN
12,Dessange,7 parvis St Maurice 59800 Lille,NaN,http://www.facebook.com/DESSANGE.Paris,https://www.instagram.com/dessangesaintmaurice...,https://salon.dessange.com/salon-coiffure/lill...,NaN,NaN
14,Dessange Esquermoise,22 r Esquermoise 59800 Lille,NaN,www.pagesjaunes.fr/pros/06174357#,https://www.instagram.com/hairexpertacademy_fr...,www.pagesjaunes.fr/pros/06174357#,NaN,NaN
16,Franck Provost,17 r Jean Roisin 59800 Lille,NaN,NaN,NaN,https://salons.franckprovost.com/fr/coiffeur/f...,4.655026e+13,NaN
19,Groupement des Commercants de Lille,157 r Nationale 59000 Lille,NaN,NaN,NaN,www.pagesjaunes.fr/pros/detail?code_etablissem...,8.903717e+13,NaN
20,Hair Coiff,47 r Postes 59000 Lille,NaN,https://www.facebook.com/pages/Hair-Coiff/2022...,NaN,NaN,8.229454e+13,NaN
22,Hair Expert Academy,782 r Cambrai 59000 Lille,NaN,NaN,NaN,https://www.hairexpertacademy.com/,9.140240e+13,NaN
24,Imagin Hair,138 r Colbert 59800 Lille,NaN,https://www.facebook.com/Imagine-Hair-Lille-10...,https://www.instagram.com/imaginehairlille/?hl=fr,NaN,4.424689e+13,NaN
26,Jimmy B,9 pl Vieux Marché aux Chevaux 59800 Lille,NaN,https://www.facebook.com/JimmyB.coiffure,https://instagram.com/jimmyb.coiffeur,NaN,8.284105e+13,NaN
29,Lamiro,63 r Tanneurs 59800 Lille,NaN,https://www.facebook.com/people/Lamiro-Barber-...,https://www.instagram.com/lamirolille/,NaN,9.928887e+13,NaN
30,Markus Paris,53 r Molinel 59800 Lille,NaN,https://www.facebook.com/MarkusParisOfficial,https://www.instagram.com/markus.paris/,https://www.markusparis.fr/,NaN,NaN
32,Palistro,5 pl Broquelet 59000 Lille,NaN,https://www.facebook.com/pages/Palistro/159790...,NaN,NaN,7.536783e+13,NaN
34,Salon Jean Louis Cacheux,4 r Tenremonde 59800 Lille,NaN,https://www.facebook.com/Salon-Jean-Louis-Cach...,NaN,http://www.jeanlouiscacheux.fr/,NaN,NaN
36,Seventies Coiffure By Bend,13 pl Nouvelle Aventure 59000 Lille,NaN,http://www.facebook.com/seventieslille,NaN,https://www.seventiescoiffurelille.fr/,7.982360e+13,NaN
38,Tchip Coiffure,14 r Esquermoise 59800 Lille,NaN,NaN,NaN,https://salons.tchip.fr/92364834844455/salon-c...,4.085334e+13,NaN

In [27]:
df.to_csv('/Users/johnpendenque/Downloads/coiffeurs_lilles.csv', index=False)

In [28]:
df[:5].to_csv('/Users/johnpendenque/Downloads/coiffeurs_lilles_2.csv', index=False)